export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import Nav from "./components/navbar"
import Footer from "./components/footer"
import { Navbar } from "@nextui-org/navbar"
import './globals.css'
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <body className="flex flex-col min-h-screen">
        <Nav/>
        {children}
       <div className="mt-auto"><Footer /></div> 
        </body>
    </html>
  )
}
