export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import Nav from "./components/navbar"
import Footer from "./components/footer"
import { Navbar } from "@nextui-org/navbar"
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <body>
        <Nav/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
